---
title: "AI Project"
author: "John Mohoang, Mitch Peterson"
date: "December 6, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(e1071)
library(tree)
library(class)
```



```{r}
music = read.csv("C:/Users/John/OneDrive/School/Mac/Comp 484 - Artificial Intelligence/Project/Aubio Fature Extractor/music.csv")

training_data = read.csv("C:/Users/John/OneDrive/School/Mac/Comp 484 - Artificial Intelligence/Project/Aubio Fature Extractor/Train.csv")

testing_data = read.csv("C:/Users/John/OneDrive/School/Mac/Comp 484 - Artificial Intelligence/Project/Aubio Fature Extractor/Train.csv")

#summary(music)
#summary(subset(music, genre == "metal")$bpm)
#summary(subset(music, genre == "reggae")$bpm)
#summary(subset(music, genre == "rock")$bpm)


# ------ Trees -----------------#

#traning and testng trees
set.seed(2)
train = sample(1:nrow(music), 800)
test = -train
#training_data = music[train, ]
#testing_data = music [test, ]


#Tree model
tree_model = tree(genre ~ ., training_data)
plot(tree_model)
text(tree_model)

  #testing 
tree_pred = predict(tree_model, testing_data, type = "class")
mean(tree_pred != testing_data$genre)

  ## Pruning 
set.seed(3)
cv_tree = cv.tree(tree_model, FUN = prune.misclass)
names(cv_tree)

plot(cv_tree$size, cv_tree$dev, type = "b", xlab = "Tree Size", ylab = "Number of Misclassified Songs")

pruned_model = prune.misclass(tree_model, best = 9.1)
plot(pruned_model)
text(pruned_model)

## Check how it is doing

tree_pred2 = predict(pruned_model, testing_data, type = "class")
mean(tree_pred2 != testing_data$genre)

#------------------------------#



#     SVM Fit           #

svm_model = svm(genre ~ ., data = training_data, kernel = "linear", cost = 10, gamma = 0)
svm_model

# Testing 
svm_pred = predict(svm_model, testing_data, type = "class")
mean(svm_pred != testing_data$genre)


#         Linear Disriminant Analysis         #
lda_model = lda(genre ~ ., data = training_data)
#lda_model

#Testing 
lda_pred = predict(lda_model, testing_data)
names(lda_pred)

lda_pred_genre = lda_pred$class

#table(lda_pred_genre, testing_data$genre)
mean(lda_pred_genre != testing_data$genre)

#---------------------#


#           QDA              #
qda_model = qda(genre ~ ., data = training_data)
qda_pred = predict(qda_model, testing_data)

qda_pred_genre = qda_pred$class

mean(qda_pred_genre != testing_data$genre)

# ------------------- # 

# The code for KNN got broken after altering the trainging and testing Data

# #        KNN            #
# std_data = scale(music[, c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62)])
# 
# new_training_data = std_data[train, ]
# new_testing_data = std_data[test, ]
# new_training_genre = training_data$genre
# 
# knn_pred = knn(new_training_data, new_testing_data, new_training_genre, 3)
# 
# mean(knn_pred != testing_data$genre)

# -------------------------- #
```



